---
name: build wheel file

on:
  push:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - edited

jobs:
  matrix:
    strategy:
      matrix:
        cfg:
        - platform:
          - os: macos-13
            arch: x86_64
            setup: x64
          python:
          - setup: "3.12"
            cibw: cp312
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      shell: python
      env:
        CFG: ${{ toJSON(matrix.cfg) }}
      run: |
        import json
        import os
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"matrix={json.dumps(json.loads(os.environ['CFG']))}\n")

  build:
    needs:
    - matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      if: ${{ matrix.platform.arch == 'aarch64' }}
      with:
        platforms: arm64

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.21.3

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_ARCHS: "${{ matrix.platform.arch }}"
        CIBW_BUILD: "${{ matrix.python.cibw }}-*"
        CIBW_SKIP: "*-musllinux_*"
        CIBW_BEFORE_ALL_MACOS: brew install swig
        CIBW_BEFORE_ALL_LINUX: yum install -y make cmake swig
        CIBW_BEFORE_BUILD: python -m pip install scikit-build
        CIBW_BUILD_VERBOSITY: 1

    - uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.python.cibw }}-${{ runner.os }}-${{ matrix.platform.arch }}
        path: ./wheelhouse/*.whl

    - if: runner.os == 'macOS'
      run: find bindings/python3

    - if: runner.os == 'macOS'
      run: cat /Users/runner/work/libsolv/libsolv/_skbuild/macosx-10.13-x86_64-3.12/cmake-build/bindings/python3/solv_python.c

  test:
    needs:
    - matrix
    - build
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: wheel-${{ matrix.python.cibw }}-${{ runner.os }}-${{ matrix.platform.arch }}
        path: dist

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      if: ${{ matrix.platform.arch == 'aarch64' }}
      with:
        platforms: arm64

    - run: docker run -v "${{ github.workspace }}:/workspace" -w /workspace --platform "${{ matrix.platform.docker }}" "python:${{ matrix.python.setup }}" python3 .github/workflows/test.py
      if: runner.os == 'Linux'

    - name: Set up Python
      uses: actions/setup-python@v5
      if: runner.os != 'Linux'
      with:
        python-version: ${{ matrix.python.setup }}
        architecture: ${{ matrix.platform.setup }}

    - if: runner.os == 'macOS'
      run: |
        sysctl -n kern.coredump
        sudo sysctl -w kern.coredump=1
        sudo chmod -R +rwx /cores/

    - if: runner.os != 'Linux'
      shell: bash
      run: |
        ulimit -c unlimited
        python -m pip install dist/*.whl
        PYTHONTRACEMALLOC=32 python .github/workflows/test.py
      continue-on-error: true

    - if: runner.os == 'macOS'
      shell: bash
      run: lldb -c $(ls -1 /cores/*) --one-line 'bt'

  release:
    needs:
    - build
    - test
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: wheel-*
        merge-multiple: true
        path: dist

    - run: find dist

    - if: ${{ startsWith(github.ref, 'refs/tags/ghrel-') }}
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.whl
